### ISSUE TITLE
Meteor integration

### ISSUE THREAD

**Issue by ackzell** [xkjyeah/vue-google-maps#26]
Hello, 

I'm trying to get vue2-google-maps to work in a Meteor project.

I have tried a lot of different ways to import the library and use it, but the dependencies are somehow not being resolved:

```

=> App running at: http://localhost:3000/

Unable to resolve some modules:

  "_" in <PATH>/vue2-google-maps.js (web.browser)
  "MarkerClusterer" in <PATH>/vue2-google-maps.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save _ MarkerClusterer
```

I've tried to declare a couple of global variables using these names ('_' and 'MarkerClusterer') according to Meteor documentation, but can't make it work. 

Also on the browser I am getting this:

```
Uncaught Error: Cannot find module '_'
    at require (http://localhost:3000/packages/modules-runtime.js?hash=637cb12b6fd3acf3ffbfcf0f2ee1cf3988a7f1fe:119:19)
    at n.(anonymous function).exports (http://localhost:3000/app/app.js?hash=c9e972a581f8948ecc022247bf873501cd0703a5:411:180)
    at meteorInstall.imports.vue2-google-maps.js (http://localhost:3000/app/app.js?hash=c9e972a581f8948ecc022247bf873501cd0703a5:412:2)
    at fileEvaluate (http://localhost:3000/packages/modules-runtime.js?hash=637cb12b6fd3acf3ffbfcf0f2ee1cf3988a7f1fe:191:9)
    at Module.require (http://localhost:3000/packages/modules-runtime.js?hash=637cb12b6fd3acf3ffbfcf0f2ee1cf3988a7f1fe:116:16)
    at Module.Mp.import (http://localhost:3000/packages/modules.js?hash=005111aa41bfbfe5e05b60f94732b2ea9f196ba4:313:16)
    at meteorInstall.client.main.js (http://localhost:3000/app/app.js?hash=c9e972a581f8948ecc022247bf873501cd0703a5:21:429)
    at fileEvaluate (http://localhost:3000/packages/modules-runtime.js?hash=637cb12b6fd3acf3ffbfcf0f2ee1cf3988a7f1fe:191:9)
    at require (http://localhost:3000/packages/modules-runtime.js?hash=637cb12b6fd3acf3ffbfcf0f2ee1cf3988a7f1fe:116:16)
    at http://localhost:3000/app/app.js?hash=c9e972a581f8948ecc022247bf873501cd0703a5:2511:1

``` 

I've received some help but still can't fix my issue: [Vue + Meteor integration](https://github.com/Akryum/meteor-vue-component/issues/95)

Any ideas?

**Comment by xkjyeah** [comment]
I'm not familiar with npm in meteor, but if you are using npm you should
have the following lines in your code:

```js
import VueGoogleMaps from 'vue2-google-maps'

Vue.use(VueGoogleMaps, {...})
```

By using import the package dependencies should be handled automatically.

**Comment by ackzell** [comment]
Thank you for the willingness to help @xkjyeah. I really want to use the library.

> By using import the package dependencies should be handled automatically.

My issue is that it _isn't_ being handled automatically. That might be due to Meteor.

Say I can't use npm. And no bundler, so according to the readme instructions I need to use the `dist` file instead, which is giving me the errors I was talking about.

Notice how I print the values of global variables `MarkerClusterer` and `_` on the console before attempting to require the code from `dist/vue-google-maps.js`

Why would it not find the `_` module? I am a bit lost here.

![image](https://cloud.githubusercontent.com/assets/601266/21537712/bb707026-cd5a-11e6-917e-cfeb3eb98e1d.png)

**Comment by xkjyeah** [comment]
_ is the lodash library. The library is exported by default as _, for
example, when you import it into your HTML from a CDN.

Why don't you add the CDN versions of marker clusterer and lodash to your
HTML?

**Comment by ackzell** [comment]
I'll try the CDN path.

But like I said, I can print out the version of lodash on my console, from the image I posted: **4.17.3**

I think that means I have it available as a global.

**Comment by xkjyeah** [comment]
That's weird. I'll do a check of the code to see if there are any undefined
instances of _.

Meanwhile, a sanity check: Did you require('vue2-google-maps') or
require('vue2-google-maps/dist/vue-google-maps')? You should be using the
former, and not the latter as suggested in the meteor-vue thread. The dist
version assumes the presence of certain globals.

**Comment by xkjyeah** [comment]
Here's something you might want to try:

1. `const VueGoogleMaps = require('vue2-google-maps')`. Do not use the `dist/` version because that requires globals, and it may not work if you are using a different version of Vue. If meteor-vue should be able to load .vue components from packages in `node_modules` directly. Language should not be an issue as I have taken care to only use HTML, JS and Babel-transpiled Javascript in all .vue components I have exported
2. If you really prefer the `dist/` version, then don't use `import`. All `import`s are interpreted first before any other statement. That means that even if you write:
```js
global._ = require('lodash')
import VGM from `vue2-google-maps/dist/vue-google-maps.js`
```
`vue2-google-maps` will still throw you an error about `_` being undefined. However, as in your situation, you will find that you will be able to use it afterwards despite the error, because by the time you access the console, the `_` has been exported. Instead, write:
```js
global._ = require('lodash')
const VGM = require(`vue2-google-maps/dist/vue-google-maps.js`)
```

Let me know how it goes.

**Comment by ackzell** [comment]
Okay, I'll be testing this and report back my findings.

Thank you for getting involved and giving me a hand :)

Awesome work on the project!

**Comment by ackzell** [comment]
I'm back at this.

So, here is the reason I tried to use the `dist` files: https://github.com/Akryum/meteor-vue-component/issues/94

Akryum suggested to do with the maps the same I did for that library [here](https://github.com/Akryum/meteor-vue-component/issues/95#issuecomment-269377928)

I have not been able to `import` nor `require` either version as of now. Haven't tried the CDN yet.

I believe the problem is that the meteor-vue integration is not liking this on the components: 

`<style lang="css">`

Still kinda lost...  will keep experimenting.

**Comment by Akryum** [comment]
@ackzell Could you try with `akryum:vue-component 0.8.5`?

**Comment by ackzell** [comment]
@Akryum Sorry for the delay. Seems like the original issue I had is gone, but still can't get a map to display on my meteor experiment project.

Pasting an image of what I see now with that version of `akryum:vue-component 0.8.5`:

![image](https://cloud.githubusercontent.com/assets/601266/22961808/71a98476-f30e-11e6-9462-0ba8027282be.png)

I would get a div which is as wide and as tall as the styles I have applied, but it renders _blank_ (not even the known issue about the gray background which is documented in the readme)

This can be reviewed at a project I set up here: https://github.com/ackzell/meteor-vue-experiment/tree/vue2-google-maps-integration

Thanks!

**Comment by xkjyeah** [comment]
After poking around a bit, I suspect meteor-vue-components don't yet
support src imports <https://vue-loader.vuejs.org/en/start/spec.html>.
Perhaps you should file a bug there.

**Comment by awitherow** [comment]
@ackzell any developments in getting a solution running?

**Comment by ackzell** [comment]
Sorry @awitherow, nothing to report. I gave up on integrating with Meteor and I'm using the Vue CLI now.

Having said that, I am still interested in knowing what could be done to fix this.

**Comment by Akryum** [comment]
vue-meteor will soon understand src imports in Vue files. I will also test myself a few popular Vue pakcages and ensure that are working correctly with meteor.

**Comment by awitherow** [comment]
no worries @ackzell and thanks @Akryum ! please let us know in some way what happens so we can close this issue up 👍  🌮

**Comment by ackzell** [comment]
I honestly haven't tried myself, but as per Akryum's comment: 

https://github.com/Akryum/vue-meteor/issues/95#issuecomment-294310294

Integration should not have issues anymore :)

**Comment by thearabbit** [comment]
I  still get error
```
If you notice problems related to these missing modules, consider running:

  meteor npm install --save MarkerClusterer

=> Errors prevented startup:

   While processing files with templating-compiler (for target web.browser):
   packages/htmljs.js:623:15: Illegal HTML attribute name: @click
   at Object.HTML.flattenAttributes (packages/htmljs.js:623:15)
   at [object Object].HTML.ToHTMLVisitor.def.visitTag (packages/htmljs.js:323:20)
   at [object Object].HTML.Visitor.def.visit (packages/htmljs.js:88:32)
```

**Comment by diegoazh** [comment]
Any change on this issue or it can be closed? it has passed almost a year since the last post about it.

**Comment by ackzell** [comment]
I'm not actively using this, not sure if @thearabbit sorted it out. Fine by me if you wanna close it.

**Comment by thearabbit** [comment]
now work fine for me (latest version)

**Comment by diegoazh** [comment]
@thearabbit the same error?
