### ISSUE TITLE
Nuxt usage - error? TypeError: Cannot set property 'render' of undefined

### ISSUE THREAD

**Issue by michaelroper** [xkjyeah/vue-google-maps#386]
Hey there!

I'm using the maps in a Nuxt project, and ever since updating to the latest version of the package the other day (was previously set to `0.8.12`, now `0.9.2`), my project gets the following error:
```
error TypeError: Cannot set property 'render' of undefined
  at normalizeComponent (node_modules/vue-loader/lib/runtime/componentNormalizer.js:24:0)
  at Object../node_modules/vue2-google-maps/src/components/map.vue (node_modules/vue2-google-maps/src/components/map.vue:13:0)
  at __webpack_require__ (webpack/bootstrap:28:0)
  at Object../node_modules/vue2-google-maps/src/main.js (node_modules/vue2-google-maps/src/main.js:1:0)
  at __webpack_require__ (webpack/bootstrap:28:0)
  at Object../plugins/vue2-google-maps.js (plugins/vue2-google-maps.js:1:0)
  at __webpack_require__ (webpack/bootstrap:28:0)
  at Object../.nuxt/index.js (.nuxt/index.js:1:0)
  at __webpack_require__ (webpack/bootstrap:28:0)
  at Object../.nuxt/server.js (.nuxt/server.js:1:0)
  at __webpack_require__ (webpack/bootstrap:28:0)
  at server-bundle.js:109:18
  at Object.<anonymous> (server-bundle.js:112:10)
  at evaluateModule (/Users/michael/Sites/vue/node_modules/vue-server-renderer/build.js:8338:21)
  at /Users/michael/Sites/vue/node_modules/vue-server-renderer/build.js:8396:18
  at new Promise (<anonymous>)
```

My Nuxt plugin looks like the following, and hasn't changed since it was previously working.
```
import Vue from "vue";
import * as VueGoogleMaps from "~/node_modules/vue2-google-maps/src/main";

Vue.use(VueGoogleMaps, {
  load: {
    key: "...",
    installComponents: false
  }
});

Vue.component("v-map", VueGoogleMaps.Map);
Vue.component("v-marker", VueGoogleMaps.Marker);
```

Do you have any ideas what might have caused the issue? Thanks...

**Comment by z46h1** [comment]
I have problems with nuxt after update. I have same imports like you and receive 3 errors: 
` warning  in ./node_modules/vue2-google-maps/dist/components/autocomplete.vue

16:2-16 "export 'default' (imported as '__vue_script__') was not found in '!!babel-loader?{"babelrc":false,"cacheDirectory":true,"presets":[["D:\\...\\node_modules\\babel-preset-vue-app\\dist\\index.common.js",{"targ
ets":{"ie":9,"uglify":true}}]]}!./autocompleteImpl.js'

 warning  in ./node_modules/vue2-google-maps/dist/components/map.vue

20:2-16 "export 'default' (imported as '__vue_script__') was not found in '!!babel-loader?{"babelrc":false,"cacheDirectory":true,"presets":[["D:\\...\\node_modules\\babel-preset-vue-app\\dist\\index.common.js",{"targ
ets":{"ie":9,"uglify":true}}]]}!./mapImpl.js'

 warning  in ./node_modules/vue2-google-maps/dist/components/streetViewPanorama.vue

20:2-16 "export 'default' (imported as '__vue_script__') was not found in '!!babel-loader?{"babelrc":false,"cacheDirectory":true,"presets":[["D:\\...\\node_modules\\babel-preset-vue-app\\dist\\index.common.js",{"targ
ets":{"ie":9,"uglify":true}}]]}!./streetViewPanoramaImpl.js'
`

**Comment by boris-glumpler** [comment]
Fixed by moving all the `*Impl.js` files in `src/components` into their respective vue components.

**Comment by xkjyeah** [comment]
Thanks for the suggestion.

My reason for keeping the `.vue` files separate from the `.js` files is that different people might have different transpilation settings.

I've figured out a way to use the library with Nuxt -- please take a look at the README and see if it helps you.

**Comment by boris-glumpler** [comment]
Thanks, but that didn't work with Nuxt Edge, which uses Webpack 4 btw: `TypeError: Cannot read property 'splice' of undefined`

**Comment by xkjyeah** [comment]
@shabushabu do you know which line of the nuxt config gives this error? Also I don't have the bandwidth to support Nuxt-edge. You can try:

```js
config.externals = config.externals || []
```

before running the `splice` operation

**Comment by michaelroper** [comment]
@xkjyeah the changes you made in 0.9.3 seem to have fixed things for me - thanks Daniel!
