### ISSUE TITLE
Error: Can't resolve 'marker-clusterer-plus'

### ISSUE THREAD

**Issue by mfferreira** [xkjyeah/vue-google-maps#49]
Getting this error after installing:
```
ERROR in ./~/vue2-google-maps/dist/components/cluster.js
Module not found: Error: Can't resolve 'marker-clusterer-plus' in './node_modules/vue2-google-maps/dist/components'
```

If I do `yarn add marker-clusterer-plus` then I get another error:
```
error during render : ./node_modules/vue2-google-maps/dist/components/map.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^
SyntaxError: Unexpected token <
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (./node_modules/vue2-google-maps/dist/components/mapElementMixin.js:11:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
(node:52424) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: window is not defined
```

**Comment by xkjyeah** [comment]
This library is meant to be used with webpack and vue-loader. You need to
configure webpack to load .vue files with vue-loader

**Comment by mfferreira** [comment]
@xkjyeah I'm using both. And that's why I was surprised by the error.

**Comment by thulioph** [comment]
The same problem here +1

**Comment by xkjyeah** [comment]
Could you paste your webpack.config.js here? Also let me know if your own
.Vue files work as expected

**Comment by Grogglex** [comment]
I'm having the same issue while using `import * as VueGoogleMaps from 'vue2-google-maps'`. Here is [my webpack config](https://raw.githubusercontent.com/centrual/cordova-template-framework7-vue-webpack/master/template_src/webpack.config.js).

```
ERROR in ./~/vue2-google-maps/dist/components/cluster.js
Module not found: Error: Can't resolve 'marker-clusterer-plus' in '/mnt/Storage/Workspace/Colibri/StrollopiaVue/node_modules/vue2-google-maps/dist/components'
 @ ./~/vue2-google-maps/dist/components/cluster.js 23:27-59
 @ ./~/vue2-google-maps/dist/main.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js ./webpack/dev_helpers/CordovaDeviceRouter.js
```

**Comment by mfferreira** [comment]
@xkjyeah this is my _webpack.base.config,js_:
```
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const path = require('path')
const webpack = require('webpack')
const vueConfig = require('./vue-loader.config')

const config = {
  devtool: '#source-map',
  entry: {
    app: './src/client-entry.js',
    vendor: [
      'es6-promise',
      'vue',
      'vue-router',
      'vuex',
      'vuex-router-sync',
    ]
  },
  output: {
    path: path.resolve(__dirname, '../dist'),
    publicPath: '/dist/',
    filename: '[name].[chunkhash].js'
  },
  resolve: {
    extensions: ['*', '.js', '.json', '.vue'],
    alias: {
      'public': path.resolve(__dirname, '../public')
    }
  },
  module: {
    noParse: /es6-promise\.js$/, // avoid webpack shimming process
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueConfig
      },
      {
        test: /\.js$/,
        loader: 'buble-loader',
        exclude: /node_modules/,
        options: {
          objectAssign: 'Object.assign'
        }
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract(['css-loader'])
      },
      {
        test: /\.styl$/,
        loader: ExtractTextPlugin.extract(['css-loader', 'stylus-loader'])
      },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract(['css-loader', 'sass-loader'])
      },
      {
        test: /\.pug$/,
        loader: ExtractTextPlugin.extract(['pug-loader'])
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: 'img/[name].[hash:7].[ext]'
        }
      }
    ]
  },
  plugins: [],
  performance: false
}

if (process.env.NODE_ENV !== 'production') {
  return module.exports = config
}

config.plugins.push(
  // this is needed in webpack 2 for minifying CSS
  new webpack.LoaderOptionsPlugin({
    minimize: true
  }),
  // minify JS
  new webpack.optimize.UglifyJsPlugin({
    compress: {
      warnings: false
    }
  })
)

module.exports = config
```

**Comment by xkjyeah** [comment]
What about vueLoader.config.js?

**Comment by mfferreira** [comment]
_vueLoader.config.js_
```
module.exports = {
  postcss: [
    require('autoprefixer')({
      browsers: ['last 3 versions']
    })
  ],
  buble: {
    objectAssign: 'Object.assign',
  },
}
```

**Comment by xkjyeah** [comment]
It's a weird error. I would try a few things:

1. Use webpack 1.x
2. Reinstall vue-loader

**Comment by xkjyeah** [comment]
3. Or use webpack 2.x if you are already using webpack 1.x

**Comment by awitherow** [comment]
https://github.com/openrefuge/openrefuge/pull/10 is the branch I am working on implementing it into a fairly new project. 

It is based on the webpack vue template generated with webpack 2.0 support.

I get this:

```
 ERROR  Failed to compile with 1 errors                                                                                                                         10:25:21 PM

This dependency was not found in node_modules:

* marker-clusterer-plus in ./~/vue2-google-maps/dist/components/cluster.js

Did you forget to run npm install --save for it?
```

**Comment by awitherow** [comment]
Idea: when we install it, the peer dependency status of the package `marker-clusterer-plus` is not working with `yarn/npm install` properly?

**Comment by xkjyeah** [comment]
Sorry guys, I haven't had time to look into this issue. If you npm install
the package, it should go away. The reason for this is simple: this library
does not *require* that specific package, and there are a number of API
compatible packages you could use, so it's not a dependency.

As for the other problem, it seems like vue-loader was not being used to
parse the .Vue file, hence the syntax error.

**Comment by alberto-bottarini** [comment]
I fix this problem manually install ```marker-clusterer-plus``` with ``` npm install --save marker-clusterer-plus ```

**Comment by thearabbit** [comment]
I base on Meteor, get error
```
If you notice problems related to these missing modules, consider running:

  meteor npm install --save MarkerClusterer

=> Errors prevented startup:

   While processing files with templating-compiler (for target web.browser):
   packages/htmljs.js:623:15: Illegal HTML attribute name: @click
   at Object.HTML.flattenAttributes (packages/htmljs.js:623:15)
   at [object Object].HTML.ToHTMLVisitor.def.visitTag (packages/htmljs.js:323:20)
   at [object Object].HTML.Visitor.def.visit (packages/htmljs.js:88:32)
```

**Comment by sunlark** [comment]
Having the same error in Meteor 

```
Unable to resolve some modules: 
  "MarkerClusterer" in /var/www/emdo/node_modules/vue2-google-maps/dist/vue-google-maps.js (web.browser)
```

I installed marker-clusterer-plus with

```
meteor npm install marker-clusterer-plus
```

and I can even successfully import this in my client-side code

```
import MarkerClusterer from 'marker-clusterer-plus';
```
I can see MarkerClusterer in browser console too,

but for some reason it still not working inside vue2-google-maps. Any ideas please?

**Comment by arenddeboer** [comment]
Running into this same issue after updating my modules. It appears webpack is looking for a folder named MarkerClusterer not, marker-clusterer-plus

**Comment by arenddeboer** [comment]
Still learning webpack so excuse my ignorance, but I was able to fix this for me with the following changes to webpack.config.js inside vue2-google-maps, essentially flipping the cluster key/value assignment:
```
/**
 * Web config uses a global Vue and Lodash object.
 * */
var webConfig = _.clone(baseConfig);
webConfig.externals = {
  vue: 'Vue',
  lodash: 'lodash',
  MarkerClusterer: 'marker-clusterer-plus'
};
webConfig.output = {
	path: path.resolve(__dirname, 'dist'),
    filename: "vue-google-maps.js",
    library: ["VueGoogleMaps"],
    libraryTarget: "umd"
};

var stubbedConfig = _.clone(baseConfig);
stubbedConfig.externals = {
    lodash: 'lodash',
    MarkerClusterer: 'marker-clusterer-plus'
};
```
Notice how I also had to change lodash.
Rebuilding requires a ```npm install``` inside vue2-google-maps to get the build tools ready, then ```npm run build``` I also removed the uglifyjs plugin as it was giving me errors...

**Comment by sunlark** [comment]
Great thanks @arenddeboer your solution works!
Just do the same steps in my Meteor app and Google Map is now working.

**Comment by beefo** [comment]
For those not using webpack installing this package worker for me: https://github.com/mahnunchik/markerclustererplus
