### ISSUE TITLE
TypeError: Cannot read property 'zoom' of null

### ISSUE THREAD

**Issue by dakshshah96** [xkjyeah/vue-google-maps#591]
I have [Sentry](https://sentry.io) error monitoring set up for my Vue.js PWA and have been receiving a lot of notifications recently with the following error:

```
TypeError: Cannot read property 'zoom' of null
  at Object.onClick (/maps-api-v3/api/js/36/4/intl/en_gb/map.js:11:125)
  at xm._.m.Ja (/maps-api-v3/api/js/36/4/intl/en_gb/common.js:135:238)
  at sm._.m.Ja (/maps-api-v3/api/js/36/4/intl/en_gb/common.js:134:175)
  at Um (/maps-api-v3/api/js/36/4/intl/en_gb/common.js:61:224)
  at HTMLDocument.Sm.W._.Em.Pa (/maps-api-v3/api/js/36/4/intl/en_gb/common.js:61:31)
...
(1 additional frame(s) were not displayed)
```

```
TypeError: Cannot read property 'zoom' of null
  at Object.onClick(/maps-api-v3/api/js/36/4/map.js:11:125)
  at xm._.m.Ja(/maps-api-v3/api/js/36/4/common.js:135:238)
  at sm._.m.Ja(/maps-api-v3/api/js/36/4/common.js:134:175)
  at Um(/maps-api-v3/api/js/36/4/common.js:61:224)
  at HTMLDocument.Sm.W._.Em.Pa(/maps-api-v3/api/js/36/4/common.js:61:31)
  at HTMLDocument.n(./node_modules/@sentry/browser/dist/index.js:3114:1)
```

Is this a bug with this package and does anyone know of any possible workarounds?

**Comment by dakshshah96** [comment]
@xkjyeah Can you help me with this if you have the time?

**Comment by DJPretorius** [comment]
Damn. Guess he didn't have the time... 
Did you find a solution in the end?

**Comment by h3** [comment]
If it can help .. I got Sentry reports for this error as well, it does not seem to affect a lot of our users, but it looks like the common denominator is Chrome 87/88;

* Chrome 88.0.4324 / Mac OS X 10.13.6
* Chrome 87.0.4280 / Mac OS X 10.15.7
* Chrome 88.0.4324 / Windows 7
* Chrome 87.0.4280 / Windows 10
* Chrome 88.0.4324 / Windows 10
