### ISSUE TITLE
500 error for unknown reason after restart computer

### ISSUE THREAD

**Issue by diamond122** [xkjyeah/vue-google-maps#635]
I tried to use vue2-google-maps and it worked well. Suddenly my computer had stopped working and then I restarted my computer. Then, strangely, 500-error comes out.

I reverted all codes associated with vue2-google-maps then my project works well.
Even though when I import vue2-google-maps then It occurs 500-error. :(
```
import * as VueGoogleMaps from 'vue2-google-maps';
```
It was working well but now cause of the unknown reason it has been broken...
Here is my console shows error.

```
webpack built 5410edae88d11b814c0b in 2690ms
error during render : /search
/media/bossminion/Work/WeMeet/frontend/node_modules/vue2-google-maps/dist/components/infoWindow.vue:3
<template>
^

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/media/bossminion/Work/WeMeet/frontend/node_modules/vue2-google-maps/dist/main.js:42:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at r (/media/bossminion/Work/WeMeet/frontend/node_modules/vue-server-renderer/build.dev.js:9295:16)
    at Object.<anonymous> (webpack:/external "vue2-google-maps":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap a442baf8af813fadc2a4:25:0)
error during render : /favicon.ico
/media/bossminion/Work/WeMeet/frontend/node_modules/vue2-google-maps/dist/components/infoWindow.vue:3
<template>
^

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/media/bossminion/Work/WeMeet/frontend/node_modules/vue2-google-maps/dist/main.js:42:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at r (/media/bossminion/Work/WeMeet/frontend/node_modules/vue-server-renderer/build.dev.js:9295:16)
    at Object.<anonymous> (webpack:/external "vue2-google-maps":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap a442baf8af813fadc2a4:25:0)
```
I posted this error in [stackoverflow](https://stackoverflow.com/questions/57063688/500-error-for-unknown-reason-after-restart-computer) but no answer yet.

**Comment by diegoazh** [comment]
The error 500 was calling the map api? the error was in local or in the server?

**Comment by diamond122** [comment]
Hi, @diegoazh  Thanks for your interest! I ran this in localhost:8080 and I don't use nuxt.

**Comment by diamond122** [comment]
I just imported `vue2-google-maps` and didn't use it. Can it be fixed by editing webpack.config.js? I have no idea. :(

**Comment by diegoazh** [comment]
The last realized version works very well, I use it in many projects. I don't think that webpack config cause this issue.
Can you provide an example in [jsfiddle](https://jsfiddle.net) or [stackblitz](https://stackblitz.com) to reproduce this issue?

**Comment by endorfin** [comment]
https://github.com/xkjyeah/vue-google-maps#nuxtjs-config

**Comment by diegoazh** [comment]
@endorfin why you post this link? @AntonioCholony said:

> Hi, @diegoazh Thanks for your interest! I ran this in localhost:8080 and **I don't use nuxt**.

**Comment by diamond122** [comment]
Hi @diegoazh In my project, when I try to use any npm module which supports ssr, 500-ssr error occurs. I can't catch what is wrong in my project. :( e.g: [vue-slider-component](https://www.npmjs.com/package/vue-slider-component)

**Comment by diamond122** [comment]
@diegoazh And in console in devTools, it says "Failed to load resource: the server responded with a status of 500 (Internal Server Error)".
And I fresh the site by pressing 'F5' and it says like below:

![image](https://user-images.githubusercontent.com/49306532/61541409-2e391f80-aa72-11e9-8a92-57ac529e01ef.png)

**Comment by diegoazh** [comment]
@AntonioCholony can you reproduce this in a small project in jsfiddle or stackblitz? That will be helpful for debug this behavior.
Are you sure that you create the project with @vue/cli?
Can you run `yarn upgrade` or equivalent `npm update --save` to update all dependencies and post your `package.json`?

**Comment by diamond122** [comment]
@diegoazh  Sorry, I have no idea how to make it in jsfiddle or stackbilitz.
```
{
  "name": "???",
  "description": "???",
  "author": "???",
  "private": true,
  "scripts": {
    "dev": "NODE_ENV=local node server",
    "start": "forever -f --minUptime 1000 --spinSleepTime 1000 server.js",
    "build:dev": "rimraf dist && npm run build-dev:client && npm run build-dev:server",
    "build:acceptance": "rimraf dist && npm run build-acceptance:client && npm run build-acceptance:server",
    "build:prod": "rimraf dist && npm run build-prod:client && npm run build-prod:server",
    "build-dev:client": "cross-env NODE_ENV=development webpack --config build/webpack.client.config.js --progress --hide-modules",
    "build-dev:server": "cross-env NODE_ENV=development webpack --config build/webpack.server.config.js --progress --hide-modules",
    "build-acceptance:client": "cross-env NODE_ENV=acceptance webpack --config build/webpack.client.config.js --progress --hide-modules",
    "build-acceptance:server": "cross-env NODE_ENV=acceptance webpack --config build/webpack.server.config.js --progress --hide-modules",
    "build-prod:client": "cross-env NODE_ENV=production webpack --config build/webpack.client.config.js --progress --hide-modules",
    "build-prod:server": "cross-env NODE_ENV=production webpack --config build/webpack.server.config.js --progress --hide-modules"
  },
  "engines": {
    "node": ">=7.0",
    "npm": ">=4.0"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "body-parser": "^1.18.3",
    "chart.js": "^2.8.0",
    "compression": "^1.7.1",
    "cookie-parser": "^1.4.4",
    "cross-env": "^5.1.1",
    "django-channels": "^1.1.6",
    "dotenv": "^7.0.0",
    "es6-promise": "^4.1.1",
    "express": "^4.16.2",
    "extract-text-webpack-plugin": "^3.0.2",
    "lru-cache": "^4.1.1",
    "route-cache": "0.4.3",
    "v-calendar": "^0.9.7",
    "v-click-outside": "^2.1.1",
    "vue": "^2.6.10",
    "vue-authenticate": "^1.4.1",
    "vue-axios": "^2.1.4",
    "vue-chartjs": "^3.4.2",
    "vue-i18n": "^8.10.0",
    "vue-moment": "^4.0.0",
    "vue-no-ssr": "^1.1.1",
    "vue-range-component": "^1.0.3", <--- 500 error
    "vue-range-slider": "^0.6.0",   <--- 500 error
    "vue-router": "^3.0.1",
    "vue-server-renderer": "^2.6.10",
    "vue-tel-input": "2.3.0",
    "vue2-google-maps": "^0.10.7",
    "vuelidate": "^0.7.4",
    "vuex": "^3.0.1",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.6",
    "babel-core": "^6.26.0",
    "babel-eslint": "^10.0.2",
    "babel-loader": "^7.1.2",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-2": "^6.24.1",
    "chokidar": "^1.7.0",
    "css-loader": "^0.28.7",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-import-resolver-webpack": "^0.11.1",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-vue": "^5.2.2",
    "file-loader": "^1.1.5",
    "forever": "^1.0.0",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "node-sass": "^4.12.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "sw-precache-webpack-plugin": "^0.11.4",
    "uglifyjs-webpack-plugin": "^1.3.0",
    "url-loader": "^0.6.2",
    "vue-loader": "^15.0.0-beta.1",
    "vue-template-compiler": "^2.6.10",
    "webpack": "^3.8.1",
    "webpack-dev-middleware": "^1.12.0",
    "webpack-hot-middleware": "^2.20.0",
    "webpack-merge": "^4.1.1",
    "webpack-node-externals": "^1.6.0"
  }
}
```

**Comment by diamond122** [comment]
I run this project by : `npm run dev`.

**Comment by diegoazh** [comment]
@AntonioCholony you are using express?

**Comment by diamond122** [comment]
@diegoazh I don't use express.

**Comment by diamond122** [comment]
@diegoazh I have found something strange. When I used ssr supported npm modules firstly, it worked well. But after few minutes, it is not working and 500 error occurs like google map and range sliders.

**Comment by diegoazh** [comment]
@AntonioCholony you are making SSR instead if you not use nuxt, please take a look the link posted for @endorfin:

> https://github.com/xkjyeah/vue-google-maps#nuxtjs-config

**Comment by AntonioCholony** [comment]
@diegoazh I think this project uses `vue-server-renderer` instead of nuxtjs. Should I close this issue? 😢

**Comment by diamond122** [comment]
Hello @diegoazh @endorfin Thank you. I have found how to handle ssr.
```
if (process.browser) {
  const VueGoogleMaps = require('vue2-google-maps');
  Vue.use(VueGoogleMaps, {
    load: {
      key: 'myKey',
      libraries: 'places',
    },
  });
}
```

**Comment by diegoazh** [comment]
If this fix the issue I will close it. Please confirm this is solved.
