### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by neeraj022** [xkjyeah/vue-google-maps#73]
I am getting the below error on importing vue2-google-maps:

```
/home/neerajy/Documents/starters/starter-source/node_modules/vue2-google-maps/dist/components/infoWindow.vue:3
<template>
^
SyntaxError: Unexpected token <
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/neerajy/Documents/starters/starter-source/node_modules/vue2-google-maps/dist/main.js:39:19)
    at Module._compile (module.js:570:32)
```

**Comment by xkjyeah** [comment]
What's your environment? You did not set up webpack.config.js correctly

**Comment by neeraj022** [comment]
I am using nuxt js framework on the top of vue.

My nuxt js configuration (default - nothing changed) is as below:


```
module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'starter',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Nuxt.js project' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Global CSS
  */
  css: ['~assets/css/main.css'],
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#3B8070' },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** Run ESLINT on save
    */
    extend (config, ctx) {
      if (ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
}
```

**Comment by neeraj022** [comment]
What should be the ideal webpack.config.js like?

**Comment by xkjyeah** [comment]
Sorry, I've no experience in that direction. This library is a pure client
side library and should be avoided for server side rendering

**Comment by atinux** [comment]
This PR #74 should fix the problem with Nuxt.js

Think to upgrade to nuxt 0.10.5 at least @neeraj022

**Comment by xkjyeah** [comment]
Ok I've published 0.7.2 with those changes.

**Comment by irobayna** [comment]
@neeraj022 @Atinux  I'm trying to use vue-google-maps with Nuxt as well.

Could you share how you pass the key into the component?

This is what I have so far:
```javascript
<script>
if (process.BROWSER_BUILD) {
  require('vue2-google-maps');
}

export default {
  middleware: 'authenticated',
  components: {
    VueGoogleMaps
  },
  mounted() {
    return
    {
      load: {
        key: 'YOUR_API_TOKEN',
        v: 'OPTIONAL VERSION NUMBER'
      }
    }
  },
  data () {
    return {
      center: {lat: 10.0, lng: 10.0},
      markers: [{
        position: {lat: 10.0, lng: 10.0}
      }, {
        position: {lat: 11.0, lng: 11.0}
      }]
    }
  }
}
</script>
```

BTW,  adding this line 
```import VueGoogleMaps from 'vue2-google-maps'```

appears to generate the following error:

```
[nuxt.js] Cannot load components TypeError: Cannot read property 'toLowerCase' of undefined
    at emptyNodeAt (eval at <anonymous> (vendor.bundle.4ed57d5….js:6), <anonymous>:4570:42)
    at VueComponent.patch [as __patch__] (eval at <anonymous> (vendor.bundle.4ed57d5….js:6), <anonymous>:5081:22)
    at VueComponent.Vue._update (eval at <anonymous> (vendor.bundle.4ed57d5….js:6), <anonymous>:2030:19)
    at VueComponent.updateComponent (eval at <anonymous> (vendor.bundle.4ed57d5….js:6), <anonymous>:2153:10)
    at Watcher.get (eval at <anonymous> (vendor.bundle.4ed57d5….js:6), <anonymous>:2464:25)
    at new Watcher (eval at <anonymous> (vendor.bundle.4ed57d5….js:6), <anonymous>:2447:12)
    at mountComponent (eval at <anonymous> (vendor.bundle.4ed57d5….js:6), <anonymous>:2157:17)
    at VueComponent.Vue$2.$mount (eval at <anonymous> (vendor.bundle.4ed57d5….js:6), <anonymous>:6803:10)
    at init (eval at <anonymous> (vendor.bundle.4ed57d5….js:6), <anonymous>:2926:13)
    at hydrate (eval at <anonymous> (vendor.bundle.4ed57d5….js:6), <anonymous>:4977:56)
```

**Comment by Remo** [comment]
@irobayna I've had the same issue, using `import VueGoogleMaps from 'vue2-google-maps'` caused a problem for me. I wanted to load things in `index.js`. Since import must be at the top I couldn't stick it in `if (process.browser) {`, but `require` works there.

This snippet can be found in my `index.js`:
```javascript
if (process.browser) {

  // window.onNuxtReady(() => console.log('Ready')) hook
  // Useful for jsdom testing or plugins (https://github.com/tmpvar/jsdom#dealing-with-asynchronous-script-loading)
  window._nuxtReadyCbs = []
  window.onNuxtReady = function (cb) {
    window._nuxtReadyCbs.push(cb)
  }

  Vue.use(require('vue2-google-maps'), {
    load: {
      key: '-',
      v: 'OPTIONAL VERSION NUMBER',
      // libraries: 'places', //// If you need to use place input
    }
  })
}
```

And then my component looks like this:

```html
<template>
  <section class="container">
    <gmap-map :center="center" :zoom="7" style="width: 500px; height: 300px">
      <gmap-marker
              v-for="m in markers"
              :key="m.id"
              :position="m.position"
              :clickable="true"
              :draggable="true"
              @click="center=m.position"
      ></gmap-marker>
    </gmap-map>
  </section>
</template>

<script>
export default {
  data () {
    return {
      center: {lat: 10.0, lng: 10.0},
      markers: [
        {
          id: 1,
          position: {lat: 10.0, lng: 10.0}
        },
        {
          id: 2,
          position: {lat: 11.0, lng: 11.0}
        }
      ]
    }
  }
}
</script>
```

**Comment by Remo** [comment]
okay, we shouldn't modify `index.js`, what we can do however is this:

in `nuxt.config.js` we can register plugins, check the end of my file:
```
module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'starter',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Nuxt.js project' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Global CSS
  */
  css: ['~assets/css/main.css'],
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#3B8070' },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** Run ESLINT on save
    */
    extend (config, ctx) {
      if (ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    },
    vendor: ['axios']
  },
  plugins: [
    // ssr: false to only include it on client-side
    { src: '~plugins/vue-google-maps.js', ssr: false }
  ]
}
```

**Comment by Remo** [comment]
My project suddenly stopped working and I couldn't figure out why. It seems like the latest version of the nuxt starter template works better, here's the commit I had to make to get things running: https://github.com/ortic/nuxt-gmaps/commit/be3262f2f9d078cc8c1817b9bb7fafa368cd8969
Hopefully my last comment on this issue..

**Comment by irobayna** [comment]
@Remo Thank you very much,  you nail it!  Works perfectly.

**Comment by cameroncrosby** [comment]
With the autocomplete the mark up should be written as directive instead of component. The server side hydration validation will fail otherwise because the components don't match.

`<input gmap-autocomplete
	  	:value="description"
		:componentRestrictions="{
			country: 'gb'
		}"
		@place_changed="setPlace" />`

**Comment by xkjyeah** [comment]
It is a component because vue directives are rather limited and that made
event handlers (@place_changed) rather hard to implement.

**Comment by xkjyeah** [comment]
I've been playing with Nuxt.js myself, and have pushed some changes.

```
npm install vue2-google-maps@latest
```

For Nuxt.js users, instead of writing:
```js
import VueGoogleMaps from 'vue2-google-maps'
```

**write**:
```js
import VueGoogleMaps from 'vue2-google-maps/dist/vue-google-maps-stubbed'
```

With this, you should be able to go back to having full server-side rendering

**Comment by cameroncrosby** [comment]
Awesome work! The import needs to be like this fyi.

`import * as VueGoogleMaps from 'vue2-google-maps/dist/vue-google-maps-stubbed'`

**Comment by xkjyeah** [comment]
I've added it to API.md. Closing this issue now.

**Comment by xkjyeah** [comment]
If you are still interested, could somebody try this solution?:
```js
import Vue from 'vue'
import * as VueGoogleMaps from '~/node_modules/vue2-google-maps'

Vue.use(VueGoogleMaps, {...})
```
(i.e. do not use the -stubbed version, but prefix the library name with ~/node_modules/

**Comment by noobling** [comment]
@xkjyeah YES that works it would be helpful if that was in the docs somewhere.

For those that still can't get it to work remember to add the plugin to plugins array in nuxt config
