### ISSUE TITLE
gmapApi import throws error on Quasar SSR mode

### ISSUE THREAD

**Issue by HimalShrestha** [xkjyeah/vue-google-maps#756]
[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token '<'
[vue-router] uncaught error during route navigation:
C:\Users\User\Documents\GitHub\p-web-upgraded\node_modules\vue2-google-maps\dist\components\infoWindow.vue:3
<template>
^

SyntaxError: Unexpected token '<'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\User\Documents\GitHub\p-web-upgraded\node_modules\vue2-google-maps\dist\main.js:42:19)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at r (C:\Users\User\Documents\GitHub\p-web-upgraded\node_modules\vue-server-renderer\build.dev.js:9310:16)
    at Object.vue2-google-maps (server-bundle.js:2628:18)

**Comment by adrianhp97** [comment]
Based on #537 need to add transplieDependencies

```
      transpile: true,

      // Add dependencies for transpiling with Babel (Array of string/regex)
      // (from node_modules, which are by default not transpiled).
      // Applies only if "transpile" is set to true.
      transpileDependencies: [
        /^vue2-google-maps($|\/)/
      ],
```

**Comment by murilolivorato** [comment]
create a boot - 

import * as VueGoogleMaps from 'vue2-google-maps'
export default ({ app, router, Vue }) => {
  Vue.use(VueGoogleMaps, {
    load: {
      key: 'YOUR-KEY',
      libraries: 'places'
    }
  })
}
