### ISSUE TITLE
Vite 3 fails on build of module

### ISSUE THREAD

**Issue by Halling69** [xkjyeah/vue-google-maps#799]
When compiling an old vue 2 project using https://github.com/vuejs/create-vue @legacy
I get the following error with vue2-google-maps@0.10.7

[vite:vue2] Could not load <project-dir>/node_modules/vue2-google-maps/dist/components/placeInputImpl.js?vue&type=script&src=true&lang.js?commonjs-exports (imported by node_modules/vue2-google-maps/dist/components/placeInputImpl.js?vue&type=script&src=true&lang.js): The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '\x00<project-dir>/node_modules/vue2-google-maps/dist/components/pl...
error during build:
TypeError [PLUGIN_ERROR]: Could not load <project-dir>/node_modules/vue2-google-maps/dist/components/placeInputImpl.js?vue&type=script&src=true&lang.js?commonjs-exports (imported by node_modules/vue2-google-maps/dist/components/placeInputImpl.js?vue&type=script&src=true&lang.js): The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '\x00<project-dir>/node_modules/vue2-google-maps/dist/components/pl...
    at Object.readFileSync (node:fs:440:14)
    at Object.load (C:\projects\sanistaal\Webshop-v4\src\Sanistaal.Website\client-vite\Ahlsell\node_modules\@vitejs\plugin-vue2\dist\index.cjs:3217:30)
    at file:///<project-dir>/node_modules/rollup/dist/es/shared/rollup.js:22748:40
ERROR: "build-only" exited with 1.

I have identified the root cause being in placeInput.vue
```
<template>
    <label>
        <span v-text="label"></span>
        <input type="text" :placeholder="placeholder" :class="className"
          ref="input"/>
    </label>
</template>

<script src="./placeInputImpl.js">
</script>
```

The other vue components  use function based require inclusion of the corresponding backend code so this code works:
```
<template>
    <label>
        <span v-text="label"></span>
        <input type="text" :placeholder="placeholder" :class="className"
          ref="input"/>
    </label>
</template>

<script>
export default (function (x) { return x.default || x })(require('./placeInputImpl.js'))
</script>
```

**Comment by aroy314** [comment]
Please let us know when this is fixed so we can close https://github.com/vitejs/vite-plugin-vue2/issues/63
